//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mymoney.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddebitoTransazioni
    {
        public int AddebitoTransazioneID { get; set; }
        public Nullable<int> TipoTransazioneID { get; set; }
    
        public virtual TipoTransazioni TipoTransazioni { get; set; }
    }
}
