//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mymoney.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conti
    {
        public Conti()
        {
            this.TransazioniConto = new HashSet<TransazioniConto>();
        }
    
        public int ContoID { get; set; }
        public int UserID { get; set; }
        public string Titolo { get; set; }
    
        public virtual ICollection<TransazioniConto> TransazioniConto { get; set; }
        public virtual Users UserProfile { get; set; }
    }
}
