//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mymoney.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoTransazioni
    {
        public TipoTransazioni()
        {
            this.AddebitoTransazioni = new HashSet<AddebitoTransazioni>();
            this.TransazioniConto = new HashSet<TransazioniConto>();
        }
    
        public int TipoTransazioneID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> EntrataUscita { get; set; }
    
        public virtual ICollection<AddebitoTransazioni> AddebitoTransazioni { get; set; }
        public virtual ICollection<TransazioniConto> TransazioniConto { get; set; }
        public virtual Users UserProfile { get; set; }
    }
}
