//------------------------------------------------------------------------------
// <auto-generated>
//    Codice generato da un modello.
//
//    Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//    Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mymoney.web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public Users()
        {
            this.webpages_Roles = new HashSet<webpages_Roles>();
            this.Conti = new HashSet<Conti>();
            this.TipoTransazioni = new HashSet<TipoTransazioni>();
        }
    
        public int UserId { get; set; }
        public string UserName { get; set; }
    
        public virtual ICollection<webpages_Roles> webpages_Roles { get; set; }
        public virtual ICollection<Conti> Conti { get; set; }
        public virtual ICollection<TipoTransazioni> TipoTransazioni { get; set; }
    }
}
